feature/SD-784
simeoncloud/docs pull request #107
Opened 2022-03-15 23:26 UTC by dawit-simeon

Updated script to add repo creation subscription

2022-03-16 22:40 UTC, jeff-simeon commented on SimeonInstaller.ps1
> +            $salesEmail = "sales@simeoncloud.com"
parameters should be PascalCase...also, call this NotificationEmail please

2022-03-17 16:41 UTC, jeff-simeon commented on SimeonInstaller.ps1
> +            $salesEmail = "sales@simeoncloud.com"
Doesn’t look like you renamed

2022-03-17 18:58 UTC, jeff-simeon submitted a review, later dismissed

2022-03-24 16:17 UTC, rdorta-simeon submitted a review, later dismissed

2022-03-25 20:08 UTC, rdorta-simeon approved these changes

2022-03-25 21:20 UTC, rdorta-simeon requested changes

2022-03-25 21:20 UTC, rdorta-simeon commented on SimeonInstaller.ps1
> +                    address = $using:NotificationEmail
No need for using here

2022-03-25 21:27 UTC, rdorta-simeon approved these changes

2022-03-25 21:39 UTC, jeff-simeon approved these changes

2022-03-26 18:08 UTC, david-simeon approved these changes

2022-03-26 18:08 UTC, merged