Feature/org install
simeoncloud/docs pull request #3
Opened 2021-02-17 15:20 UTC by Lance-Simeon

2021-02-21 04:05 UTC, admin-simeon requested changes

2021-02-21 04:05 UTC, admin-simeon commented on OrgInstaller.ps1
> +            Write-Information "Creating DevOps Organization: $Organization"
I don't suppose there is any way at all to make this a non-AAD connected org in the REST request?

2021-02-21 04:05 UTC, admin-simeon commented on OrgInstaller.ps1
> +        $projectId = ((Invoke-WithRetry { Invoke-RestMethod -Header $AuthenicationHeader -Uri "https://dev.azure.com/$Organization/_apis/projects?api-version=6.1-preview.4" -Method Get }).value |? {
might just extract to Get-AzureDevOpsProjectId $Organization...and could cache the result (see how SimeonInstaller does this for tenant ids)...you're getting ProjectId over and over again

2021-02-21 04:05 UTC, admin-simeon commented on OrgInstaller.ps1
> +        Invoke-WithRetry { Invoke-RestMethod -Header $AuthenicationHeader -Uri "https://dev.azure.com/$Organization/_apis/FeatureManagement/FeatureStates/host/project/$projectId/ms.vss-work.agile?api
only do this if it's a new org

2021-02-21 04:05 UTC, admin-simeon commented on OrgInstaller.ps1
> +    $projectId = ((Invoke-WithRetry { Invoke-RestMethod -Header $AuthenicationHeader -Uri "https://dev.azure.com/$Organization/_apis/projects?api-version=6.1-preview.4" -Method Get }).value |? { $_.n
why are you doing this again?

2021-02-21 04:05 UTC, admin-simeon commented on OrgInstaller.ps1
> +                    "url": "https://dev.azure.com/$Organization/$ProjectName/_settings/settings",
Call $Project to be consistent with SimeonInstaller.

2021-02-21 22:27 UTC, admin-simeon commented on OrgInstaller.ps1
> +            Invoke-WithRetry { Invoke-RestMethod -Headers $AuthenicationHeader -ContentType "application/json" -Method Post -Uri "https://aexprodcus1.vsaex.visualstudio.com/_apis/HostAcquisition/Coll
aexprodcus1 is for central us - I think you want aex.dev.azure.com to be region agnostic at least for the host

2021-03-02 04:38 UTC, admin-simeon reviewed
Nice code!

2021-03-02 04:38 UTC, admin-simeon commented on SimeonInstaller.ps1
> +            [string]$Organization,
add validation attributes to parameters like other cmdlets

2021-03-02 04:38 UTC, admin-simeon commented on SimeonInstaller.ps1
> +        $AuthenicationHeader = @{Authorization = "Bearer $token" }
camelCase

2021-03-02 04:38 UTC, admin-simeon commented on SimeonInstaller.ps1
> +            Write-Host "Getting project id for Organization: $Organization project: $Project"
no Write-Host (Write-Verbose or Write-Information or WriteWarning)

2021-03-02 04:38 UTC, admin-simeon commented on SimeonInstaller.ps1
> +            Write-Information "Limiting job authorization scope to current project for non-release pipelines"
aren't you doing the OPPOSITE? "uncheck Limit job authorization scope to current project for non-release pipelines "

2021-03-09 20:25 UTC, admin-simeon requested changes

2021-03-09 20:25 UTC, admin-simeon commented on SimeonInstaller.ps1
> +                Write-Verbose "Disconnecting Organization from Azure Active Directory"
why verbose?

2021-03-09 20:25 UTC, admin-simeon commented on SimeonInstaller.ps1
> +        $groups = (Invoke-WithRetry { Invoke-RestMethod -Header $authenicationHeader -Uri "https://vssps.dev.azure.com/$Organization/_apis/graph/groups?api-version=6.1-preview.1" -Method Get }).value
you shouldn't assume this variable is defined in a parent scope - each function should get its own auth header

2021-04-30 04:52 UTC, Lance-Simeon commented
Branch is out of date

2021-04-30 04:52 UTC, closed without merging