feature/SD-3314 - Updated Updated Resource Info
simeoncloud/docs pull request #674
Opened 2024-09-11 22:10 UTC by packages-simeon

2024-09-17 13:57 UTC, rdorta-simeon requested changes

2024-09-17 13:57 UTC, rdorta-simeon commented on providers-auth.md
> +- M365 Admin Center > Settings > Org Settings > Microsoft Forms
M365 Admin Center providers are forcing delegated auth

2024-09-17 13:57 UTC, rdorta-simeon commented on providers-auth.md
> +## Configurations managed with a service principal
Can we alphabetically order the providers? Also might be usefull to add their namespace. For example MSGraph:Groups to make it easier to build filters based on this document. @brad-Simeon @Lance-Simeon

2024-09-23 14:50 UTC, rdorta-simeon approved these changes

2024-09-23 16:59 UTC, Lance-Simeon approved these changes

2024-09-23 16:59 UTC, merged