Feature/job pipelines
simeoncloud/docs pull request #9
Opened 2021-04-23 04:19 UTC by Lance-Simeon

Update installer script to support summary and retry pipelines from the jobs repo. Once this PR is approved, I will also be merging the Org Install to master.

2021-04-23 22:35 UTC, admin-simeon requested changes
👍

2021-04-23 22:35 UTC, admin-simeon commented on SimeonInstaller.ps1
> +        $gitConfig = "-c http.extraheader=`"AUTHORIZATION: bearer $token`""
perhaps we should set this in git config inside Get-GitRepository
```
git config http.extraheader=`"AUTHORIZATION: bearer $token`"
```

2021-04-23 22:35 UTC, admin-simeon commented on SimeonInstaller.ps1
> +        Push-Location (Get-GitRepository $GitSourceUrl)
always use try/finally with Push/Pop location

2021-04-23 22:35 UTC, admin-simeon commented on SimeonInstaller.ps1
> +        Write-Information "Installing repo: $RepoName for $organization"
```
        Write-Information "Installing repository '$RepoName' for '$Organization'"
```

terms are quoted and $Organization capitalization was wrong

2021-04-23 22:35 UTC, admin-simeon commented on SimeonInstaller.ps1
> +    function Install-DevOpsRepoFromGitHub {
`Install-SimeonTenantRepository` should use this, no?

2021-04-23 22:35 UTC, admin-simeon commented on SimeonInstaller.ps1
> +    function Install-DevOpsRepoFromGitHub {
`Install-DevOpsRepositoryFromGitHub`

2021-04-24 01:34 UTC, Lance-Simeon commented on SimeonInstaller.ps1
>      function Get-AuthenticationHeader {
Don't remember talking about it, this function is only used for the org install for the moment. If we want to support PAT tokens beyond the org installer, we can expand everything to use this function. Was trying to keep changes to a minimum for this effort

2021-04-24 04:30 UTC, JeffN825 commented
But doesn’t that encoding and way of basic auth work for bearer tokens too? I thought you had inadvertently tried it and found it to work?

________________________________
From: Lance T ***@***.***>
Sent: Friday, April 23, 2021 6:34:57 PM
To: simeoncloud/docs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [simeoncloud/docs] Feature/job pipelines (#9)


@Lance-Simeon commented on this pull request.

________________________________

In SimeonInstaller.ps1<https://github.com/simeoncloud/docs/pull/9#discussion_r619561940>:

> @@ -562,9 +562,9 @@ CRLFOption=CRLFAlways
     function Get-AuthenticationHeader {


Don't remember talking about it, this function is only used for the org install for the moment. If we want to support PAT tokens beyond the org installer, we can expand everything to use this function. Was trying to keep changes to a minimum for this effort

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/simeoncloud/docs/pull/9#discussion_r619561940>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AB7NDFPKX5M3SKSBR3LNLATTKIN4DANCNFSM43N3LBCA>.

2021-04-25 01:20 UTC, admin-simeon commented on SimeonInstaller.ps1
>      function Get-AuthenticationHeader {
But doesn’t that encoding and way of basic auth work for bearer tokens too? I thought you had inadvertently tried it and found it to work?

2021-05-10 03:17 UTC, merged